name: version
description: Provides a simple class for parsing and comparing semantic versions
  as defined by http://semver.org/
version: 2.0.0
homepage: https://github.com/dartninja/version

environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  lint: ^1.8.2
  test: ^1.16.3
