name: Publish package to pub.dev
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_OAUTH_REFRESH_TOKEN }}",
            "idToken":"${{ secrets.PUB_OAUTH_ID_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1614537527097
          }
          EOF
      - name: Publish package
        run: pub publish -f