name: Dart CI

on:
  push:
    branches: [ nullsafety ]
  pull_request:
    branches: [ nullsafety ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:beta
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
